### ISSUE TITLE
Covid Tracker Android App

### ISSUE THREAD

**Issue by fosterer** [DevilsAutumn/Hacktoberfest22#31]
**Title**
Covid Tracker Android App

**Project link**
[Click here](Paste link of project here)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [x] App with Java
- [ ] App with Kotlin
- [ ] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
Android Application to track the covid cases in a state or any of its district.
**Describe the solution you'd like**
The app provides a precise tracking facility to the users about the number of active cases, deaths , recovered cases in a state and districts.
**Additional context**
NA.

**Comment by saikatdgp2001** [comment]
Sorry to say , please don't contribute as it is excluded from Hacktoberfest 2022.

**Comment by Akash-moon** [comment]
Hello @DevilsAutumn Please assign me this project under hacktoberfest22.
I have done this project already.

**Comment by DevilsAutumn** [comment]
> Hello @DevilsAutumn Please assign me this project under hacktoberfest22.
> I have done this project already.

This repo has been excluded from hacktoberfest.

**Comment by Akash-moon** [comment]
Thanks for confirming.
