### ISSUE TITLE
to add an alert in todo

### ISSUE THREAD

**Issue by nikhil730** [DevilsAutumn/Hacktoberfest22#41]
**Title**
To add an alert in todo

**Project link**
[Click here](Paste link of project here)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
So till now if we enter on empty input value then if will not do anything,  but if we add an alert then user will get an idea what he/she has to do.

**Describe the solution you'd like**
Adding an simple alert if the input value is empty will do the job

**Additional context**
Add any other context or screenshots about the feature request here else write NA.
![Screenshot (5)](https://user-images.githubusercontent.com/79016958/194380957-39d6a5ed-802f-42ea-a456-f6217078071b.png)

**Comment by DevilsAutumn** [comment]
Great 👍
